### ISSUE TITLE
Conversion from native text on Windows

### ISSUE THREAD

**Issue by patperry** [patperry/r-corpus#5]
I'm not sure if this is a bug or not. In general, R has trouble with character encodings on Windows. See https://github.com/juliasilge/tidytext/issues/80 .

I implemented a partial work-around in `as_utf8`. It seems to work correctly when the native locale is English:

<img width="532" alt="screen shot 2017-08-24 at 5 27 36 pm" src="https://user-images.githubusercontent.com/43450/29689795-82d1b8ca-88f2-11e7-808c-c2ec9d3e5e43.png">

When the declared locale is wrong, you get weird results, but I think that is the fault of RStudio:

<img width="521" alt="screen shot 2017-08-24 at 5 32 02 pm" src="https://user-images.githubusercontent.com/43450/29689821-95198436-88f2-11e7-97a8-961ba66e3270.png">

It would be great if someone with a non-English Windows machine could test this.

CC @kristel-  @juliasilge @prokulski

**Comment by patperry** [comment]
Oh btw, if you want to copy paste:

```r
x <- c("aä", "õu", "aa", "bb", "ös", "ll", "üks", "vv", "žs", "zz", "šk")
```

(above are screenshots from a windows VM)

**Comment by patperry** [comment]
I fixed the third case above, so that `corpus::as_utf8` works correctly regardless of the locale

**Comment by kristel-** [comment]
Hi Patrick, thanks for reporting and investigating the issue, my results in RStudio version 1.0.143 and in R seem to be the same, but slightly different from yours:

![rstudio-utf](https://user-images.githubusercontent.com/3889274/29784680-99d5dfd6-8c2d-11e7-97f3-aa7d78c6cf8b.JPG)

and in R:

![r-utf](https://user-images.githubusercontent.com/3889274/29784820-255b2688-8c2e-11e7-8368-330859674659.JPG)

> sessionInfo()
R version 3.4.0 (2017-04-21)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 15063)

Matrix products: default

locale:
[1] LC_COLLATE=Estonian_Estonia.1257  LC_CTYPE=Estonian_Estonia.1257    LC_MONETARY=Estonian_Estonia.1257 LC_NUMERIC=C                     
[5] LC_TIME=Estonian_Estonia.1257    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] corpus_0.9.1

loaded via a namespace (and not attached):
[1] compiler_3.4.0  Matrix_1.2-9    grid_3.4.0      lattice_0.20-35
>

**Comment by patperry** [comment]
Thanks for testing, @kristel- ! I forgot to mention that this is with a development version of corpus, not the one on CRAN. Could you try installing the development version and re-testing, following the instructions at https://github.com/patperry/r-corpus#building-from-source ?

**Comment by patperry** [comment]
Also, if any of the output is not as you expected, please report the results of `lapply(x, charToRaw)`.

No need for screenshots (unless that's easier for you); copy-paste is fine.

**Comment by kristel-** [comment]
In R, the problem remains with the locale C and characters _ž_ and _š_. In RStudio, the problem seems to be in Rstudio and the same characters get distorted already in outputting, but get handled fine with the conversion, except again with the locale C.

In R:

> x <- c("aä", "õu", "aa", "bb", "ös", "ll", "üks", "vv", "žs", "zz", "šk")
> x
 [1] "aä"  "õu"  "aa"  "bb"  "ös"  "ll"  "üks" "vv"  "žs"  "zz"  "šk" 
> Sys.setlocale("LC_CTYPE", "")
[1] "Estonian_Estonia.1257"
> corpus::as_utf8(x)
 [1] "aä"  "õu"  "aa"  "bb"  "ös"  "ll"  "üks" "vv"  "žs"  "zz"  "šk" 
> 
> Sys.setlocale("LC_CTYPE", "C")
[1] "C"
> corpus::as_utf8(x)
 [1] "aä"  "õu"  "aa"  "bb"  "ös"  "ll"  "üks" "vv"  "þs"  "zz"  "ðk" 
> 
> Sys.setlocale("LC_CTYPE", "Estonian_Estonia.1257")
[1] "Estonian_Estonia.1257"
> corpus::as_utf8(x)
 [1] "aä"  "õu"  "aa"  "bb"  "ös"  "ll"  "üks" "vv"  "žs"  "zz"  "šk" 
> 
> lapply(x, charToRaw)
[[1]]
[1] 61 e4

[[2]]
[1] f5 75

[[3]]
[1] 61 61

[[4]]
[1] 62 62

[[5]]
[1] f6 73

[[6]]
[1] 6c 6c

[[7]]
[1] fc 6b 73

[[8]]
[1] 76 76

[[9]]
[1] fe 73

[[10]]
[1] 7a 7a

[[11]]
[1] f0 6b

and in RStudio:

> x <- c("aä", "õu", "aa", "bb", "ös", "ll", "üks", "vv", "žs", "zz", "šk")
> x
 [1] "aä"  "õu"  "aa"  "bb"  "ös"  "ll"  "üks" "vv"  "þs"  "zz"  "ðk" 
> Sys.setlocale("LC_CTYPE", "")
[1] "Estonian_Estonia.1257"
> corpus::as_utf8(x)
 [1] "aä"  "õu"  "aa"  "bb"  "ös"  "ll"  "üks" "vv"  "žs"  "zz"  "šk" 
> Sys.setlocale("LC_CTYPE", "C")
[1] "C"
> corpus::as_utf8(x)
 [1] "aä"  "õu"  "aa"  "bb"  "ös"  "ll"  "üks" "vv"  "þs"  "zz"  "ðk" 
> Sys.setlocale("LC_CTYPE", "Estonian_Estonia.1257")
[1] "Estonian_Estonia.1257"
> corpus::as_utf8(x)
 [1] "aä"  "õu"  "aa"  "bb"  "ös"  "ll"  "üks" "vv"  "žs"  "zz"  "šk" 
> lapply(x, charToRaw)
[[1]]
[1] 61 e4

[[2]]
[1] f5 75

[[3]]
[1] 61 61

[[4]]
[1] 62 62

[[5]]
[1] f6 73

[[6]]
[1] 6c 6c

[[7]]
[1] fc 6b 73

[[8]]
[1] 76 76

[[9]]
[1] fe 73

[[10]]
[1] 7a 7a

[[11]]
[1] f0 6b


> sessionInfo()
R version 3.4.1 (2017-06-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 15063)

Matrix products: default

locale:
[1] LC_COLLATE=Estonian_Estonia.1257  LC_CTYPE=Estonian_Estonia.1257    LC_MONETARY=Estonian_Estonia.1257 LC_NUMERIC=C                      LC_TIME=Estonian_Estonia.1257    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] corpus_0.9.1.9000

loaded via a namespace (and not attached):
[1] compiler_3.4.1  Matrix_1.2-10   grid_3.4.1      lattice_0.20-35
>

**Comment by patperry** [comment]
Thanks for the update! It's hard to tell if this is working or not. One of the counter-intuitive things about R is that the statement
```r
x <- c("aä", "õu", "aa", "bb", "ös", "ll", "üks", "vv", "žs", "zz", "šk")
```
will give you different results depending on your locale. Let's look at just three of the characters.

### Windows-1252
```r
> Sys.setlocale("LC_CTYPE", "") # set the character encoding to my native one, Windows-1252
"English_United States.1252"
> x <- c("ü", "ž", "š")
> Encoding(x)
[1] "latin1" "latin1" "latin1"
lapply(x, charToRaw)
[[1]]
[1] fc

[[2]]
[1] 9e

[[3]]
[1] 9a
```
The characters get encoded in my native locale (https://en.wikipedia.org/wiki/Windows-1252#Character_set ) but declared as Latin-1, a subset of Windows-1252. Right now, I'm working around the bug in `as_utf8` by decoding Latin-1 as Windows-1252.

### C locale

```r
> Sys.setlocale("LC_CTYPE", "C")
[1] "C"
> x <- c("ü", "ž", "š")
> Encoding(x)
[1] "unknown" "UTF-8" "UTF-8"
apply(x, charToRaw)
[[1]]
[1] fc

[[2]]
[1] c5 be

[[3]]
[1] c5 a1
```

Now the characters have different encodings. R's handling of the C locale is a little weird. Anything marked as "unknown" means either ASCII or your native locale. I think it tries to translate the input to Latin-1, and where this is not possible, it codes the input as UTF-8. (The ü characters is in Latin-1, but ž and š are not). You can verify that the UTF-8 encodings for the latter two are correct at http://graphemica.com/%C5%BE and http://graphemica.com/%C5%A1 .

### Windows-1257

```r
> Sys.setlocale("LC_CTYPE", "Estonian_Estonia.1257")
[1] "Estonian_Estonia.1257"
> x <- c("ü", "ž", "š")
> Encoding(x)
[1] "unknown" "unknown" "unknown"
> lapply(x, charToRaw)
[[1]]
[1] fc

[[2]]
[1] fe

[[3]]
[1] f0
```

These strings get coded as "unknown", but now that the `LC_CTYPE` is Windows-1257, uknown refers to that encoding. We can verify that the encodings are correct at https://en.wikipedia.org/wiki/Windows-1257#Character_set. R has trouble displaying these characters, because the declared encoding is different from the system encoding (Windows-1252):

```r
print(x)
[1] "ü" "þ" "ð"
```

When printing, R assumes that the `LC_CTYPE` is your native locale, but this is not the case here. R prints the `fe` and `f0` Windows-1252 characters (https://en.wikipedia.org/wiki/Windows-1252#Character_set ).

The `utf8_print` function fixes this:
```r
corpus::utf8_print(x)
[1] "ü", "ž", "š"
```

### Summary

All this is to stay that, in your test above, it's hard to interpret the results. When you set `LC_CTYPE`, it does not modify any of your existing data; `Encoding(x)`; and `lapply(charToRaw, x)` will give the same results. What changes is (a) how R translates your input; and (b) how R interprets the `"unknown"` encoding.

It would help if you re-did the assignment `x <- c("ü", "ž", "š")` after setting `LC_CTYPE`, and if you printed `Encoding(x)` and `lapply(x, charToRaw)` for each set of results.

**Comment by patperry** [comment]
Oh, also, if you have time, it'd be nice if you could find out what happens when you set
```r
Sys.setlocale("LC_CTYPE", "English_United States.1252")
```
since this is not your native encoding. Setting `Sys.setlocale("LC_CTYPE", "")` asks for the native encoding; on your computer, this is equivalent to `Sys.setlocale("LC_CTYPE", "Estonian_Estonia.1257")`.

**Comment by kristel-** [comment]
Thanks for the guidelines and sorry abou the mess. I also included `print` outputs (see output of `corpus::utf8_print(x)` with the locale C).

Everything is the same in R and RStudio except the output of the `print`, which is ok in R, but not in RStudio.

Pleas let me know, if I missed something.

## RStudio
``` r
> Sys.setlocale("LC_CTYPE", "")
[1] "Estonian_Estonia.1257"
> x <- c("ü", "ž", "š")
> Encoding(x)
[1] "unknown" "unknown" "unknown"
> lapply(x, charToRaw)
[[1]]
[1] fc

[[2]]
[1] fe

[[3]]
[1] f0

> 
> print(x)
[1] "ü" "þ" "ð"
> library(corpus)
> corpus::utf8_print(x)
[1] "ü" "ž" "š"
> 
> rm(list=ls(all=T))
> detach("package:corpus", unload=TRUE)
> 
> Sys.setlocale("LC_CTYPE", "C")
[1] "C"
> x <- c("ü", "ž", "š")
> Encoding(x)
[1] "unknown" "UTF-8"   "UTF-8"  
> lapply(x, charToRaw)
[[1]]
[1] fc

[[2]]
[1] c5 be

[[3]]
[1] c5 a1

> 
> print(x)
[1] "ü" "ž" "š"
> library(corpus)
> corpus::utf8_print(x)
[1] "\u00fc" "\u017e" "\u0161"
> 
> rm(list=ls(all=T))
> detach("package:corpus", unload=TRUE)
> 
> Sys.setlocale("LC_CTYPE", "English_United States.1252")
[1] "English_United States.1252"
> x <- c("ü", "ž", "š")
> Encoding(x)
[1] "latin1" "latin1" "latin1"
> lapply(x, charToRaw)
[[1]]
[1] fc

[[2]]
[1] 9e

[[3]]
[1] 9a

> 
> 
> print(x)
[1] "ü" "ž" "š"
> library(corpus)
> corpus::utf8_print(x)
[1] "ü" "ž" "š"
```

## R
 ```r
> Sys.setlocale("LC_CTYPE", "")
[1] "Estonian_Estonia.1257"
> x <- c("ü", "ž", "š")
> Encoding(x)
[1] "unknown" "unknown" "unknown"
> lapply(x, charToRaw)
[[1]]
[1] fc

[[2]]
[1] fe

[[3]]
[1] f0

> 
> print(x)
[1] "ü" "ž" "š"
> library(corpus)
> corpus::utf8_print(x)
[1] "ü" "ž" "š"
```

**Comment by patperry** [comment]
Great, thanks for reporting back @kristel- .

I think what you're telling me is that both `corpus::as_utf8` and `corpus::utf8_print` work correctly in `R` and `RStudio`, in all locales you tested. (By design, `corpus::utf8_print` will only print ASCII characters in the "C" locale and replace others with `\uXXXX` escapes.) The problem with `print` is a bug in RStudio; unfortunatley, not there's not much we can do about that other let RStudio know about the problem (please do this if you have the time).

In the meantime, I think you can solve your original problem with inputting data to `tidytext` by just changing your text encoding from native to UTF-8 by sending the result of `corpus::as_utf8` to `tidytext::unnest_tokens`.

I'm going to close the issue, but please report back if anything is not working correctly. Thank you for reporting the issue, and for testing the fix.

**Comment by dpprdan** [comment]
The print bug seems to be resolved in [RStudio v1.1](https://blog.rstudio.com/2017/10/09/rstudio-v1.1-released/)

Sys.setlocale("LC_CTYPE", "Estonian")
#> [1] "Estonian_Estonia.1257"
x <- ("ü", "ž", "š")
print(x)
#> [1] "ü" "ž" "š"

<details><summary>Session info</summary>

``` r
devtools::session_info()
#> Session info -------------------------------------------------------------
#>  setting  value                       
#>  version  R version 3.4.2 (2017-09-28)
#>  system   x86_64, mingw32             
#>  ui       RTerm                       
#>  language (EN)                        
#>  collate  German_Germany.1252         
#>  tz       Europe/Berlin               
#>  date     2017-10-10
#> Packages -----------------------------------------------------------------
#>  package   * version date       source                          
#>  base      * 3.4.2   2017-09-28 local                           
#>  compiler    3.4.2   2017-09-28 local                           
#>  datasets  * 3.4.2   2017-09-28 local                           
#>  devtools    1.13.3  2017-08-02 CRAN (R 3.4.1)                  
#>  digest      0.6.12  2017-01-27 CRAN (R 3.4.2)                  
#>  graphics  * 3.4.2   2017-09-28 local                           
#>  grDevices * 3.4.2   2017-09-28 local                           
#>  memoise     1.1.0   2017-05-29 Github (hadley/memoise@e372cde) 
#>  methods   * 3.4.2   2017-09-28 local                           
#>  stats     * 3.4.2   2017-09-28 local                           
#>  tools       3.4.2   2017-09-28 local                           
#>  utils     * 3.4.2   2017-09-28 local                           
#>  withr       2.0.0   2017-09-07 Github (jimhester/withr@eff4818)
#>  yaml        2.1.14  2016-11-12 CRAN (R 3.4.2)
```

</details>

**Comment by patperry** [comment]
Excellent, thanks for reporting.
